.github/workflows/label.yml, .github/workflows/manual.yml, .github/workflows/stale.yml
Patch from #5 #8 #4 #7 and #3 to main by @DamianSwanAAJHS2
=> Actions patch

docs/filecreator.html, docs/index.html
=> Patch creator using durable links

functions/.eslintrc.js
Directory that can fetch and list cred files
=> [ Feature ] : Credential Directory

README.md
Update [Readme.md](https://github.com/DamianSwanAAJHS2/SillyLittleFiles/blob/90d1e7796f378a2dd19427edb2b525011d8d4bea/README.md) to match 90d1e77
https://github.com/DamianSwanAAJHS2/SillyLittleFiles/blob/90d1e7796f378a2dd19427edb2b525011d8d4bea/README.md?plain=1#L1-L8
Closes #131
=> [ Hot Fix ] : Update README.md

.github/workflows/restyle-tag.yml
Add Script to add a `restyle-pr` tag to Restyle bot PRs
=> [ Enhancement Prod ] : Create restyle-tag.yml

.github/workflows/restyle-tag.yml, docs/star.js
Fixed JS documentation to resolve JSD1001
It is recommended to have documentation comments above, or right inside a function/class declaration. This helps developers, users and even the author understand the purpose of a code snippet or API function in the future. **NOTE**: If you want to stop this issue from getting raised on certain constructs (arrow …
There are 16 occurrences of this issue in the repository.
See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/DamianSwanAAJHS2/SillyLittleFiles/issue/JS-D1001/occurrences/](https://app.deepsource.com/gh/DamianSwanAAJHS2/SillyLittleFiles/issue/JS-D1001/occurrences/)
Bug introduced in PR #35 
Resolves #39
=> [ Hot Fix JS ] : Repair Broken Docs JSD1001

.github/workflows/labler.yml
https://github.com/DamianSwanAAJHS2/SillyLittleFiles/security/code-scanning/1
Closes 143
=> [ Bug Vundz ] : To fix CWE-94

.github/dependabot.yml
Patched Dependabot.yml to contain package-ecosystem.
=> [ Patch ] : Patched Dependabot.yml

.github/dependabot.yml
=> [ HOTFIX BUG ] : Patch Depbot

docs/1.html, docs/11.html, docs/404.html, docs/directory.html, docs/downloader.html, docs/filecreator.html, docs/index.html
<p style="font-style:italic;">Contact: technical@sillylittle.tech</p>
=> [ Enhancement ] : Add contact footers to pages

.github/workflows/main_sillylol.yml
Updated Azure web app artifact so it zips for faster uploading™
=> [ HotFix ] : Update AZWA for faster artifact zipping™

.github/workflows/deploy-preview.yml
Broken Code, make issue and fix later
=> [ Temp Fix ] : Comment out Dependabot Ignore

docs/1.html, docs/11.html, docs/404.html, docs/directory.html, docs/downloader.html, docs/filecreator.html, docs/index.html
Adding Google Analytics to Firebase website
=> [ Feature ] : Google Analytics

docs/editjsn.html
Needs links merged into branch, Ready for review once merged.
=> [ Feature ] : JSON Editor in Web

docs/tools/filecreator.html
Other ports seem to work fine for access to Proton Tunnel, so I added the option in the file creator
=> [ Feature ] : Add PORT option to filecreator

docs/style.css
Fixes unused and redundant styles in /docs/style.css
Closes #189
=> [ Style ] : Remove Redundant Styles

docs/style.css
Patch broken stylesheet introduced in #197 
(Really should have watched the preview on that one lmao)
Invalidates #199
=> [ Patch ] : Patch broken stylesheet #197

docs/tools/filecreator.html
Merged "Let 'em Cook", "New Project", and "Download" buttons into the first in file creator. 
Hopefully this would make making files as minimally confusing as possible.
=> [ Enhancement ] : Merge File Creator buttons

docs/star.js, docs/tools/filecreator.html, docs/tools/filecreator.js
Splits the filecreator.html /tool/ into Filecreator.httml and filecreator.js instead of having a long script tag in the main hyper
=> [ Style ] : Split Filecreator JS

README.md, docs/index.html, docs/tools/index.html
Add GOTOOL details and links into web
=> [ Feature ] : Go Site

docs/discussions/220.html, docs/discussions/index.html
=> [ Discussion ] : Discussion page for #220

docs/discussions/1.html, docs/discussions/11.html, docs/discussions/190.html, docs/discussions/193.html, docs/discussions/220.html, docs/discussions/index.html, docs/index.html, docs/tools/directory/serverlister.html, docs/tools/editjsn.html, docs/tools/filecreator.html, docs/tools/index.html
=> [ Style ] : Add Metadata for pages

docs/index.html, docs/tools/index.html
=> [ Style ] : Change outlinks in tools to assume domain info

docs/index.html, docs/tools/index.html
Links did not use the right variable lol, most likely because I changed some things in reused code, but didn't affirm everything
=> [ Hotfix ] : Patch links not using the proper variable

SECURITY.md
Add a security.md file and merge it into dependent PR #237
=> [ Merge ] : Merge Security.md into cfnamechange

.github/ISSUE_TEMPLATE/Enhancer.md, .github/ISSUE_TEMPLATE/bug_report.md, README.md, SECURITY.md, docs/discussions/1.html, docs/discussions/11.html, docs/discussions/190.html, docs/discussions/193.html, docs/discussions/220.html, docs/index.html, docs/tools/directory/serverlister.html
- Changed Codefactor link references to fix link breakage
- Changed Github links for cleanup
- Did not change other links for possible caching. 
- Contacted DeepSource Support for comment
- Posted on SonarCloud Forums for [comment on](https://community.sonarsource.com/t/changed-github-account-name-should-i-be-concerned/116601).
- Closes #236
=> [ Hotfix ] : Code Factor Name Change

.github/workflows/deploy-preview.yml, .github/workflows/deploy-prod.yml, .github/workflows/restyle-tag.yml, package-lock.json, package.json
See #263 for more details on PR
=> [ Dependencies ] : Merge SLF Deps into Main

README.md, docs/tools/index.html
https://github.com/dswan36/sillylittle.selfhost/pull/11
&
https://github.com/dswan36/acprox/pull/39
=> [ Feature ] : Link to EZPROX in tools and RM

LICENSE
Pls
- Updates the data on the license `2024 -> 2024-2025`
=> [ License ] : Update Date on license

docs/robots.txt
Request Bytespider Ignore crawling via c7f87035472608a4fbf7c3142062cab478a27b61 [docs/robots.txt](https://github.com/dswan36/SillyLittleFiles/blob/c7f87035472608a4fbf7c3142062cab478a27b61/docs/robots.txt)
Erm, Would switch to Vercel for site hosting if weren't so close to #267
Resolves #275 for now.
=> [ Style ] : Request Bytespider ignore crawling

CODE_OF_CONDUCT.md, SECURITY.md
- Update SecPolicy to reflect other policy changes
- Add COC with linkback to docs COC page
=> [ Style ] : Update SecPolicy and add COC

docs/tools/index.html
=> [ Tool ] : Add email request button

docs/star.js
Resolves https://github.com/dswan36/SillyLittleFiles/issues/342
=> [ Smells ] : Cleanup code for DST

LICENSE
=> [ Chore ] : Update LICENSE to 2025+

docs/tools/directory/serverlister.html, docs/tools/filecreator.css, docs/tools/filecreator.html
- Adds a filecreator stylesheet
- Fixes link text on filecreator
=> [ Style ] : Fix link text on filecreator & add stylesheet.

docs/tools/directory/serverlister.html
=> [ Style ] : Floating `'` in File Creator

docs/discussions/301.css, docs/discussions/301.html, docs/discussions/301.js, docs/tools/directory/serverlister.css, docs/tools/directory/serverlister.html, docs/tools/directory/serverlister.js, docs/tools/filecreator.css
- Adds a table of contents to #301
=> [ Formatting ] : Add TOC (Table of Contents) to #301

.github/ISSUE_TEMPLATE/Enhancer.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/dependabot.yml, SECURITY.md, docs/discussions/1.html, docs/discussions/11.html, docs/discussions/190.html, docs/discussions/193.html, docs/discussions/220.html, docs/discussions/301.css, docs/discussions/301.html, docs/discussions/301.js, docs/discussions/index.html, docs/index.html, docs/tools/directory/serverlister.css, docs/tools/directory/serverlister.html, docs/tools/directory/serverlister.js, docs/tools/filecreator.css, docs/tools/filecreator.html, docs/tools/filecreator.js, package-lock.json
- Update name in GH links
- Add Anchors to #301 
- Add buttons to copy anchors added to #301
=> [ Style ] : Name Change + Anchors on #301

docs/discussions/index.html, docs/index.html
- Warning text looks kind of goofy in its current state. Perhaps revisit later?
=> [ Style ] :Remove warning text from /d/index

docs/tools/index.html, docs/tools/securly.html
Adds a Securly Blocklist Checker tool
=> [ Feature ] : Securly Blocklist Checker
